# Generated by Django 4.2.5 on 2023-10-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('section_desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=150)),
                ('product_desc', models.TextField(max_length=200)),
                ('product_unit_barcode_no', models.CharField(max_length=200)),
                ('outer_product_case_barcode', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_section', to='base.productsection')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('product_last_action', models.CharField(max_length=200)),
                ('product_last_update', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='base.products')),
            ],
        ),
    ]
