# Generated by Django 4.2.5 on 2023-10-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Dispatched',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('dispatch_quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dispatch', to='base.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dispatch', to='base.products')),
            ],
        ),
    ]
